# Generated by Django 3.2.4 on 2022-01-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionexpert',
            name='expert_detail',
            field=models.TextField(null=True, verbose_name='专家详情'),
        ),
    ]
